### ISSUE TITLE
Serverjumping (last glitches)

### ISSUE THREAD

**Issue by BlockBuster019** [StarQuestMinecraft/StarQuestPublic#1086]
So first i wanted to compliment you guys on the fix of server jumping, it was fast and its good you fixed the dying.. There are 3 more glitches though.
1. My new ship has about 1900-2000 blocks and this doesn't let it go into space for some reason, the server says its preparing server jump but it doesn't do it.
2. When i go into space with my smaller fighter, i get teleported back into orbit the second i move, i think this is because the teleportation radius is too big and we're teleported too close to the planet.
3. When i get teleported back into orbit theres a small chance of me losing all signs, doors, anything thats not wool or slabs of any kind.

Hope this report helped ya guys, and good luck! ^-^
-Block

**Comment by Millibyte1** [comment]
1, 2) It couldn't find a suitable location for your ship. I'm going to expand the search radius out so that it will fis both of these issues.

3) Do you know if any of your signs had colors on them?

**Comment by AnonymousLemur** [comment]
When do you think that this might be fixed? Cause I'm stuck on quillion and I need to sell stuff and whatnot.

**Comment by Millibyte1** [comment]
Not sure, priority #2 bug

**Comment by mcdouble** [comment]
In regards to the leaving atmosphere and being teleported right back in wherever you try to move, I posted a bug about this issue with Arator a long time ago but I believe it was closed because not many had experienced it at the time. But yes, this is an issue. I mostly only experience it with Arator, and sometimes Jurion. I know Kyorg said he experiences it with Beskytt.
