### ISSUE TITLE
[Private] Signs Error

### ISSUE THREAD

**Issue by GroxTerror** [StarQuestMinecraft/StarQuestPublic#223]
Appears a player was able to cut off my private doors and tow my ship. No idea how but something may have broken when Dib tried making it so any block that forms the door can have a private sign (appears to be broken also)

**Comment by lawrencethefrog** [comment]
Was it your their town, your base, or the wilderness? Town assistants have the */plot clear* command which is intended for clearing locked doors. It deletes all signs on that chunk, regardless of what they have on them. If it was your base, it should not have been possible. If it is their town they have every right to do so. If it is in the wilderness they could (but probably wouldn't) create a temporary town/town outpost to do */plot clear* in, though in that case they have to respect the land claiming rules, such as not claiming within a certain area of other claims without permission.

**Comment by GroxTerror** [comment]
Wilderness, on my shields ship

**Comment by lawrencethefrog** [comment]
Well then it is possible they made a temporary town outpost just to destroy your sign, though that is unlikely as embassy plots cost quite a lot. It is not, however, completely out of the question if they suspected your ship was worth a lot or was carrying valuable cargo they could not somehow steal otherwise. Also, was the ship a privateclad? if so, a mod could well have destroyed it.
Do you have any idea where your ship was towed or who towed it? If so, it might be a good idea to go there and collect further evidence, and maybe ask them how they did it.

**Comment by GroxTerror** [comment]
It was a friend, in the middle of space, right next to a planet, in no claim.

**Comment by Siigillum** [comment]
Sometimes those private doors bug and are not detected while you activate a ship I guess. Happened to me a few times. rare case though.

**Comment by GroxTerror** [comment]
Hmmm... I've been thinking about this and I've realized something. Maybe when the shield deactivated due to me flying another ship, it also deleted the sign permissions?

**Comment by Dibujaron** [comment]
This was fixed, thanks for reporting.
