### ISSUE TITLE
Ship shields not working in dock in W/G

### ISSUE THREAD

**Issue by awangatboo** [StarQuestMinecraft/StarQuestPublic#229]
I have a standard W/G that I make on most planets.  It has a hanger for my ship.  I have changed my ship to have a ship shield sign.  The shields work on this ship when not in my W/G.  It does not work or power up in my W/G even with a doc.  I have gone in my W/G and made a doc and even when I run the /rg info command I see the two different regions.   

[09:56:49] [Client thread/INFO]: [CHAT] You're standing in several regions, and WorldGuard is not sure what you want.
[09:56:49] [Client thread/INFO]: [CHAT] You're in: @dock_awangatboo@-682,134,1649, ahome

I plan on leaving this setup in place on Bole for a while so someone can look at this.  TP to x=-675,y=136,x=1654 to see the setup.  The [shield] sign is on the left side of the ship.

**Comment by Dibujaron** [comment]
This is intentional due to the way shields work. If you park your ship in your home worldguard, your shield will not turn on, because it's already protected by the worldguard. Docks are intended for when you want to park in other peoples' towns and factions and they only work for towns and factions. The check for docks in worldguards was too costly, so you have to rely on your ship fitting all of the way within the worldguard. Sorry. :(
