### ISSUE TITLE
Can't join StarQuest

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#234]
It says Can't Connect to server when I hover over it and it gives me

io.netty.channel.ConnectTimeoutException: connection timed out:

and everyone else says they are online and able to play.

**Comment by awangatboo** [comment]
I have had this issue before and as I remember correctly one of two things fixed it.

#1 a new minecraft install.  
#2 In my case when I tried to login (on a diffrent server) it would kick me with that message.  The issue was something to do with the chunk that made the client never receive the info it needed.  I could tell this as when I would try to login TheBeaver (my son) was already logged in and could see that it looked like I logged in even though I had not.  The fix was to get a TP to a different location during the time where I was trying to login.

Not sure if any of these Ideas will help but thought I would give you my experience in case it helps.

**Comment by HiFlyCS** [comment]
NEVERMIND it was just an error

**Comment by HiFlyCS** [comment]
Oo i can close things lol

**Comment by HiFlyCS** [comment]
Nevermind it was just an error
