### ISSUE TITLE
Pigs are not getting tamed on Valadro

### ISSUE THREAD

**Issue by soronthar** [StarQuestMinecraft/StarQuestPublic#441]
McDoubleAwesome reported that he tried to tame the pigs using carrots, but they didn´t get the pig tag on them. He then tried to breed them, with no sucess.

I tested taming some pigs, and I only got to breed them, but they hade no tags.

**Comment by mcdouble** [comment]
As an extension of this, cows have their tag for me (probably because I had them before this bug), but upon breeding, they chew up my wheat but don't produce mini baby cows. 

For the pigs, I brought them to the pen, bred them, they took the carrots and had hearts (like when they normally breed correctly). Results: No pig tag, no baby pigs. 

You can make this a low priority fix, but it'd still be nice to have it fixed so if I sort out my machina issues I'll have pork and beef to supply the furnace array.

**Comment by TotallyNotSatan** [comment]
Same thing with chickens on Krys.

**Comment by Dibujaron** [comment]
Thanks for reporting. This is fixed.
