### ISSUE TITLE
Bosk Ship Bug Strikes Again

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#468]
Flying back to Bosk after I did a merchant contract in my gunship. Upon entering, I fall from the ship spawn level and die of the fall damage. I have no proof to corraborate this incident other than the word of lOOney20 and Jusaplayer1.
I'm not expecting anything back as I have no screenshot, but at the very least this might help to fix the bug.

**Comment by Kyle98martin** [comment]
Happened to me twice yesterday when I entered Bosk

**Comment by JUSAPlayer1** [comment]
Happened to looney the same day but feather falling boots saved him. I myself also fell later that evening (late last night) but since I had leather in my hot bar I was able to save myself. This bug has stolen at least 7 sets of gear from my guys thus far and combined with the void lag issue which hit Kyle 2-3 times and looney20 1-2 times we've lost far too much gear to this stuff.

**Comment by ghost** [comment]
Happened to me on entry to bole, thankfully I recovered my stuff thanks to my death marker.

**Comment by JUSAPlayer1** [comment]
Happened to me on bole last night
But thanks to people deciding to fly into the chunk to be complete you know what's in combination with me being sent back to bosk, my items were gone.

**Comment by awangatboo** [comment]
Is this still an issue on SQ 3.0?

**Comment by awangatboo** [comment]
Closing as an SQ 2.0 bug.  If this is happening in SQ 3.0 please open a new ticket
