### ISSUE TITLE
3.0 Ship spawning

### ISSUE THREAD

**Issue by Nixx59** [StarQuestMinecraft/StarQuestPublic#497]
When I spawned into 3.0, I spawned my ship and then someone else spawned a ship into mine and i lost m legacy sign. I had also had another ship inside of mine.

**Comment by awangatboo** [comment]
Dib already said that at the beginning of SQ 3.0 legacy ships were a use at your own risk with no refund.  I lost mine because the ship sign did not convert.  TheBeaver lost his because another ship spawned inside of his.  I did not get a refund and TheBeaver did not get a refund either.  In short I think no one will get help / refund on this please close this github ticket so Dib can get to the important ones that cause issues for the whole server.

**Comment by awangatboo** [comment]
Legacy ship issues will not be fixed.  Closing ticket
