### ISSUE TITLE
Lightfreighter didn't transfer correctly 

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#498]
My friend Kridec recently loaded the lightfreighter that he had saved. When loaded in, the ship was marked as lightfreighter even though it had more than 600 blocks. Therefore it couldn't be piloted by Kridec. When i looked at the ship transfer table it says it should have been FRR (Freighter).

**Comment by awangatboo** [comment]
Dib already said that at the beginning of SQ 3.0 legacy ships were a use at your own risk with no refund.  I lost mine because the ship sign did not convert.  TheBeaver lost his because another ship spawned inside of his.  I did not get a refund and TheBeaver did not get a refund either.  In short I think no one will get help / refund on this please close this github ticket so Dib can get to the important ones that cause issues for the whole server.

**Comment by awangatboo** [comment]
Legacy ship issues will not be fixed.  Closing ticket.
