### ISSUE TITLE
Ship Spawning

### ISSUE THREAD

**Issue by Die508** [StarQuestMinecraft/StarQuestPublic#500]
I had my /saveship spawn but it spawn into i other ship and its completly in the other ship
plz leave me a comment

Die508

**Comment by awangatboo** [comment]
Dib already said that at the beginning of SQ 3.0 legacy ships were a use at your own risk with no refund.  I lost mine because the ship sign did not convert.  TheBeaver lost his because another ship spawned inside of his.  I did not get a refund and TheBeaver did not get a refund either.  In short I think no one will get help / refund on this please close this github ticket so Dib can get to the important ones that cause issues for the whole server.
