### ISSUE TITLE
Killed coming into Trinitos Alpha

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#549]
A few minutes ago i flew into Trinitos Alpha from Trinitos Beta. Then i came to the slipgate my ship simply disappeared (maybe going into TA), i was given a chat message that said it couldnt connect to default or fallback server and my inventory was wiped, and left me floating at the slipgate. I died of suffocation.

**Comment by awangatboo** [comment]
This is what happens when a java server is down.  90% of the time you die, your ship makes it through.  The best thing to do is then ask a mod to TP you to the system when it comes back up.  If they do this it will restore your inventory.  In the case you logout when a mod is not online make sure you do not pilot another ship because if you do there is almost no chance to get your ship back.  Also any refunds should be directed to the Mods.  GitHub is for Bugs.  As this was a one time server down bug please close this issue.

**Comment by awangatboo** [comment]
Closing as Server have been up and down since then and this should fix the issue.
