### ISSUE TITLE
Tree farms don't work.

### ISSUE THREAD

**Issue by Psych0bob** [StarQuestMinecraft/StarQuestPublic#606]
Simply put, making a tree farm doesn't work currently.

Checked tutorial to make sure I was using it correctly, I was, but the sign doesn't change when right clicked.

**Comment by Scooter5131** [comment]
This is a duplicate post to #539 that I opened 18 days ago.

**Comment by awangatboo** [comment]
I think I heard @nickmist say that someone messed up the perms on this.  You have the perms to operate one but no to create the sign.  This means that if somehow one was made you could operate it.  This does need to be fixed.

**Comment by Scooter5131** [comment]
I see that this issue now has a tag as Under Review, and I was wondering if there are any estimates on when it will be resolved as it's almost a month and a half since it was first reported.

I realize that we are technically in SQ 3.0 Beta (I think), and it takes some time to work out bugs/issue, but it would be nice to actually receive some feedback on the status of the issue.

Thank you,
Scooter5131

**Comment by awangatboo** [comment]
I talked to NickMiste about this yesterday about this and he has fixed it in a Test server but need to check SQ and make surre it works.

**Comment by Scooter5131** [comment]
Verified that this is not working as of 8/17/2015.

Any updates on the testing and when it might be implemented.

Thanks,
Scooter5131

**Comment by awangatboo** [comment]
I have been talking to Nick about this.  The issue is that the Plugin TreeFarm is having issues with another plugin.(it works by itself in a test world)  The question is which plugin.  I bug Nick about this on TS about once a day.  It is being worked on but trying to find the plugin it has issues with and then figuring out why they do not work together will take time.

**Comment by awangatboo** [comment]
I just got word that they figured out what was causing the issue but it is another SQ plugin so there might not be an easy fix.

**Comment by Nickmiste** [comment]
Fixed. Sorry for taking so long
