### ISSUE TITLE
Ship Shield Timer

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/StarQuestPublic#623]
Ship shield messages continue to say "Your shield failed to activate" even while unpiloted. Unsure if this is a timer bug or simply an automatic message. 
I've also seen, but unable to test to see if a bug, ship shields not activating if the player has left while it is warming up. Has anyone had a similar experience?

**Comment by awangatboo** [comment]
Every time you stop your ship it starts the 5 min timer.  The issue is most people will stop and start the ship many times trying to land it in the exact spot.  If you stop/start 5 times then you will see 4 "Your shield failed to activate"

Not sure this is a bug but more of something users need to understand.  Dib can make the call of if it is a Bug.

**Comment by Siigillum** [comment]
It's how the system works.

**Comment by awangatboo** [comment]
This is not a bug but as @Siigillum it is just how it works.  Closing this issue.
