### ISSUE TITLE
F Chat

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#625]
Faction Chat is broken, not sure if this is intended or what

**Comment by awangatboo** [comment]
No it is not intended but when you are using a Bungee chat program that has not been updated since ~2013 you can have issues.  

In short if you want faction chat to be working ask a Mod to reload chat.  When they do this it should fix it.

The long term fix is to put in a new chat system.  Ripping out the old Chat and putting in a new one would not be that easy as there are functions that everyone is used to and making sure this new chat had all the same features and worked better than the current one.  My hunch is we just need to live with this until the Dev's have nothing else to do in which case they can work on a new chat system.

**Comment by awangatboo** [comment]
Closing this ticket as a know issue.
