### ISSUE TITLE
Contract not completing

### ISSUE THREAD

**Issue by JavaInvader** [StarQuestMinecraft/StarQuestPublic#670]
This is a Report for xGirl_Archerx. A piracy contract for 1 fighter data core at gamma south does /contract complete # and it says "Completing Contract!" but does not complete. Apparently this is not the first time this has happened and they lost 20k for removing the contract.

**Comment by GirlArcher** [comment]
Um it was not 20k from just that contract it was from another Data core contract that would also not let me do the contract

**Comment by Thedrew655** [comment]
There are a few things that need to occur in order to complete a contract, firstly the contents need to be placed in a dropper, secondly you must be within the station in which you are completing the contract, thirdly you must have the correct contract number. Most of the time its the wrong number because the contract numbers change depending on how many you have open, if you close one, the numbers change.

**Comment by awangatboo** [comment]
I am closing this ticket as it is not a repeatable bug.  If it get to the point that this can be repeated then we can ask the Devs to check the logs.

**Comment by JavaInvader** [comment]
This problem is when they do /contract complete # it Will say "Completing contract!" But will not Successfully complete the contract. The Player is still having this problem.
