### ISSUE TITLE
Cant use drills

### ISSUE THREAD

**Issue by Ashen44** [StarQuestMinecraft/StarQuestPublic#671]
so, I am aware that recently the side certs such as drills, treefarms, and other such items were removed and the perms activated for everyone, but I can't use them. at least, I can't use drills. I haven't tested any of the others, so I don't know yet. I would enjoy if this were fixed as soon as possible because it's delaying my construction quite a bit. Thanks.

**Comment by awangatboo** [comment]
From 

http://www.starquestminecraft.com/starquesthome/m/17590832/article/3406188/page/2

"The machina/turret certs have also been changed. They have been condensed down to 3 combat and 3 trading. Now here's where it gets tricky. Due to the changes made you may have to repurchase any of these you have bought. Sorry for the inconvinence but I don't think there's a way to make them auto update."

This means that they have not been removed.  Please check your certs.

**Comment by awangatboo** [comment]
OK I looked to far down on the front page.  

http://www.starquestminecraft.com/starquesthome/m/17590832/article/3426032

This says you should be able to use them.  I am checking with staff to see what is going on.

**Comment by awangatboo** [comment]
I have been told the perms should be correct now.  Could you please check and let us know if it is working?

**Comment by awangatboo** [comment]
Someone else checked and they work now.
