### ISSUE TITLE
Ship Redirecting

### ISSUE THREAD

**Issue by shadyninja21** [StarQuestMinecraft/StarQuestPublic#689]
I know for a fact that this bug happens when flying straight up. I've had it happen for other directions too but it isn't as consistent.

Basically, to recreate this bug you will need the following:
Spaceship (Always happens in my courier and shuttles/fighters too, I'd imagine all ships get it)
Ship Controller

Place your ship on the ground and enter it. Pilot your ship, and then proceed to fly straight up until it randomly redirects you and you fly a sideways/downward direction. 

It happens on Otavo and Nalavor for sure to my memory. Might happen in other places as well.

**Comment by awangatboo** [comment]
Oh I think I know what this is.  This is due to LAG.  Not sure if it is your PC LAG or the Internet or the times the Server LAGs.  Here is the issue.  Sometime when LAG occurs and you get TP's to the new location (movecraft) and it can not remember which way you should be facing and when that happens it put you in the same location as when you hit the ship sign and then you start going this way.  When I LAG when I am in space that happens all the time.  I always end up looking up as that is the way I was looking when I first come into space.  Can you test this to see if we are talking about the same thing?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
