### ISSUE TITLE
A cursing bug, you can curse just by adding S to the end of it

### ISSUE THREAD

**Issue by Crazan21** [StarQuestMinecraft/StarQuestPublic#702]
you can say any curse word that is blocked if you add an S to the end of it

example: f##ks, b#st#rds, sh#ts (except without the hashtags lol, just didn't wanna curse)

any of them just with an s. might wanna patch it.

**Comment by JavaInvader** [comment]
Jane's Swear filter needs updated

**Comment by awangatboo** [comment]
I asked Dib about this.  His response was 

From: Dibujaron
"writing really effective swear filters is extremely hard, hers is just cursory 
 still relies on mods to be there, she just gets the low hanging fruit"

Because of this I am going to close this ticket and Java that means more work for you.
