### ISSUE TITLE
Falling in Space

### ISSUE THREAD

**Issue by ScaredCarrot** [StarQuestMinecraft/StarQuestPublic#734]
I'm not sure if this is a bug or not, but sometimes, when in space, I'll fall into the void. The server doesn't "catch" me most of the time, so I loose all of my items.

**Comment by awangatboo** [comment]
If you fall into the void then something is wrong.  If there is a block above you and a block below you then you will fall but you should die on the block below you.

**Comment by ScaredCarrot** [comment]
I fell into the void. Everything went black except for that weird square of visibility above you, like when you fall into the void. I also fell for a while, and instead of taking damage steadily, I took a lot of damage extremely fast.

**Comment by Evancooldude** [comment]
Issues like this have happened to me in the past. The answer is almost always extreme lag. The system that space uses for gravity can be occasionally glitchy, but in almost all cases your best bet is to log out as soon as you notice any gravity glitches that aren't due to blocks being above and below you. Relog, and the system may catch you. 

Has this issue been resolved?

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
