### ISSUE TITLE
Died on Loyavas, had a Cryopod spawned on Rakuria

### ISSUE THREAD

**Issue by rakso10000** [StarQuestMinecraft/StarQuestPublic#794]
Today (5th January 2016), I flew with my space ship to Loyavas and had a Cryopod on it. I exited the ship and died due to fall damage, then I respawned at the Rakuria spawn. I already reported this to a mod (Holly) she/he tried to help me, but he needed the coordinates of my ship at Loyavas and I didnt know them and also didnt find them at the dynmap. Then he/she said I should report it here. A friend will bring me to Loyavas now, I hope I will get my Items back and the bug will be fixed.

**Comment by HollywoodSun** [comment]
I asked him if he was on that spot in Rakuria with his ship prior to going to Loyavas and he said no. So, what I originally thought with the whole changing your cryopod location by repiloting is not the case.

**Comment by Mindaugas3** [comment]
Cryo's need fix. Just make a cryo spawn invalid if after one part of it has been destroyed. It will solve many problems regarding svs/explosions/booms and stuff like that.

**Comment by Evancooldude** [comment]
The problem with cryopods is that that system is what we should have in
place. The issue comes into play with "How do you tell when the thing you
blew up was a cryopod?". The answer is that we can't just run around
testing every time an explosion goes off, if the thing blown up was a
cryopod piece. In most cases when a cryopod is blown up, to my knowledge,
it works fine. It's that 1% that's a problem.

**Comment by awangatboo** [comment]
I have heard one of the Jr. Dev's has been looking through dib's code to see if they can find a better way to deal with this but I do not think a fix is coming any time soon.

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
