### ISSUE TITLE
Moving really fast in space.

### ISSUE THREAD

**Issue by Beachguyryan** [StarQuestMinecraft/StarQuestPublic#804]
Today Gokuva and attacker15 got into a fight, Gokuva was moving around in space really fast as if in flying. He says he's not hacking and doesn't know why it's happening.

**Comment by Gokuva** [comment]
Whenever i exit my spaceship, i experiance regular creative flight, instead of the slow flight that i should receive. Because of this, i had an unfair advantage over attacker15 and i killed him, even tho he had full protection 4 chain armor. I request that this glitch is fixed, and that attacker, aswell, gets his items back. If this turns out not to be a glitch, you have full permission to ban me and i will not appeal. What i will fight for, is that Attacker15 or ghost gets his items back.

**Comment by lawrencethefrog** [comment]
Thank you for being honest. A manager will have to decide whether you are in trouble or not, but thanks for reporting the bug (which it does seem to be). 
Any additional details about the bug would be helpful, though I'm not sure that there is much more that you would be able to observe. Does this high-speed flight still happen whenever you space walk?

**Comment by Gokuva** [comment]
Yes. Whenever i am not in a ship, but in space i have the regular creative speed instead of the slow. And whatever decision you make, i will respect.

**Comment by Mindaugas3** [comment]
This. When I first intercepted Gokuva, he was also moving very very fast. I could barely hit an AP shot because of the speed/latency(even despite the fact that i shot in front of him)

**Comment by Gokuva** [comment]
^

**Comment by awangatboo** [comment]
Closing all bugs in preparation for SQ 4.0.
