### ISSUE TITLE
Citizenship Lottery Possible Easy Exploit

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#829]
I haven't actually tested this, but based on my entering the empire citizenship lottery, you should easily be able to enter as someone else, as it only requires a username. I don't think this is the exploit Dibujaron was talking about, because he said you would have to be tech savvy, and it would take hours to do, but just filling out a few forms for other people so they join a different empire than you know they wanted would take only a few minutes. If you did it on a different network there would be no way to track who did it to ban them. 

I'm not sure how this could be solved, but it would probably require it to be done on a forum account linked to their mc account, or in-game, somehow. i hope this doesn't delay the start of 4.0, but if it's not fixed and people abuse it, it would cause a bunch of headache for mods and devs trying to fix the problems it could make. Thanks,

Cutout

**Comment by StarQuestMinecraft** [comment]
That's it. It takes hours because your IP is blocked from filling out more than one form every few hours. If you're tech savvy and know how to change IPs quickly you can do it faster. However, it's noticeable when this is done and as I said on the frontpage, all you'll accomplish from doing this is pushing the release back 24 hours, along with unconditional permanent bans for you and anyone who helped you. Please don't waste my time by doing this.
